### ISSUE TITLE
App with dependency com.mikepenz:aboutlibraries:14.0.0 does not build

### ISSUE THREAD

**Issue by AndyDekiert** [mikepenz/AboutLibraries#1330]
Updating from com.mikepenz:aboutlibraries:13.2.1 to v14.0.0 is not possible because build throws the following error:
```
Execution failed for task ':app:processDebugResources'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform aboutlibraries-14.0.0.aar (com.mikepenz:aboutlibraries:14.0.0) to match attributes {artifactType=android-compiled-dependencies-resources, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=aar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for AarResourcesCompilerTransform: /Users/andreas/.gradle/caches/9.3.1/transforms/0dd33dadaededa137bef720bec530505/transformed/aboutlibraries-14.0.0.
         > Resource compilation failed (Failed to compile resource file: /Users/andreas/.gradle/caches/9.3.1/transforms/0dd33dadaededa137bef720bec530505/transformed/aboutlibraries-14.0.0/res/color-v21/description_divider.xml: . Cause: javax.xml.stream.XMLStreamException: ParseError at [row,col]:[1,1]
           Message: Vorzeitiges Dateiende.). Check logs for more details.
```

I assume the error is caused by 41f1a916adca3a68fe2feb0a0a9d2bfdaa3cb098, which added the mentioned file `res/color-v21/description_divider.xml`. However the file is empty.

**Comment by mikepenz** [comment]
Very strange 🤔 . I guess it's a sign that I finally should remove the view based module, and only move forward with the compose module. 

In all seriousness though, I unfortunately don't know what could cause that. I suspect either it's an incompatibility of some jetpack libraries, or a change of AGP9

**Comment by AndyDekiert** [comment]
Dropping the view based module entirely would be kind of unfortunate.. E.g. the app I am developing currently does not use compose at all. So the easy integration of the view based module is very much welchome.

What are the empty files under `aboutlibraries/src/main/res/color-v21` for anyways? My guess is that gradle is just failing because the v21 files are empty and either adding some content or deleting them would fix it.

**Comment by mikepenz** [comment]
actually that is a good pointer. let me have a dive into it

**Comment by mikepenz** [comment]
Please retry with 14.0.1, let me know if that fixed it

**Comment by AndyDekiert** [comment]
I just tried 14.0.1 and it works like a charm again. Thanks very much for the quick replies and the fix.

**Comment by mikepenz** [comment]
Thanks for reporting it, and actually solving it for me :P
